  strcpy(s[0],"COMMAND LINE");
  strcpy(s[1]," -p           : play");
  strcpy(s[2]," --colors     : force color usage");
  strcpy(s[3]," --nocolors   : B&W, for dummy terminals (telnet)");
  strcpy(s[4]," --autoscr    : force autodetect the screen's size");
  strcpy(s[5]," --noautoscr  : don't autodetect the screen's size");
  strcpy(s[6]," --fakelines  : draw lines on terminals without ACS");
  strcpy(s[7]," --new_start  : start with default configuration");
  strcpy(s[8],"");
  strcpy(s[9],"PLAYER");
  strcpy(s[10]," z            : previous");
  strcpy(s[11]," x            : play");
  strcpy(s[12]," c            : pause");
  strcpy(s[13]," v            : stop");
  strcpy(s[14]," b            : next");
  strcpy(s[15]," s            : Shuffle On/Off");
  strcpy(s[16]," <ENTER>      : Play ");
  strcpy(s[17]," <SPACE BAR>  : Set As Next ");
  strcpy(s[18]," <TAB>        : Add/Remove to/from filter ");
  strcpy(s[19]," <LEFT>       : Backward 1%");
  strcpy(s[20]," <RIGHT>      : Forward 1%");
  strcpy(s[21]," <            : Backward 5%");
  strcpy(s[22]," >            : Forward 5%");
  strcpy(s[23]," f            : On/Off persistent filter ");
  strcpy(s[24]," F            : Clear filter ");
  strcpy(s[25]," r            : Repreat current song ");
  strcpy(s[26]," i or ALT+3   : ID3v1.1 TAG Editor (for selected song)");
  strcpy(s[27]," I            : ID3v1.1 TAG Editor (for current song))");
  strcpy(s[28]," j or F3      : Jump to file");
  strcpy(s[29]," <INSERT>     : Volume + ");
  strcpy(s[30]," <DELETE>     : Volume - ");
  strcpy(s[31]," <HOME>       : PCM + ");
  strcpy(s[32]," <END>        : PCM - ");
  strcpy(s[33]," ,            : Balance left ");
  strcpy(s[34]," .            : Balance right ");
  strcpy(s[35]," e            : Equalizer");
  strcpy(s[36]," A            : Automatic Equalizer On/Off");
  strcpy(s[37]," '            : Repaint Desktop");
  strcpy(s[38]," *            : Increase desktop width");
  strcpy(s[39]," /            : Decrease desktop width");
  strcpy(s[40]," +            : Increase desktop height");
  strcpy(s[41]," -            : Decrease desktop height");
  strcpy(s[42]," t            : Switch clock display mode");
  strcpy(s[43]," \\            : Change Password");
  strcpy(s[44]," !            : Lock Display");
  strcpy(s[45]," =            : Cycle Status Bar Modes");
  strcpy(s[46]," h or F1      : Help");
  strcpy(s[47]," ?            : About and Statistics");
  strcpy(s[48]," {            : Set Alarm On Time");
  strcpy(s[49]," }            : Set Alarm Off Time");
  strcpy(s[50]," T            : Set Sleep mode");
  strcpy(s[51]," |            : On/Off Shut Down mode");
  strcpy(s[52]," o            : Settings");
  strcpy(s[53]," ESC          : Screen Saver");
  strcpy(s[54]," ALT+SHIFT+Q  : Quit");
  strcpy(s[55],"");
  strcpy(s[56],"PLAYLIST");
  strcpy(s[57]," a            : Add File");
  strcpy(s[58]," d            : Delete File");
  strcpy(s[59]," D            : Add Directory");
  strcpy(s[60]," R            : Delete All");
  strcpy(s[61]," S            : Sort Playlist");
  strcpy(s[62]," <UP>         : Cursor Up");
  strcpy(s[63]," <DOWN>       : Cursor Down");
  strcpy(s[64]," <PAGE UP>    : Page Up");
  strcpy(s[65]," <PAGE DOWN>  : Page Down");
  strcpy(s[66]," 0..9         : Fast Scroll");
  strcpy(s[67]," [            : Move Up");
  strcpy(s[68]," '            : Move Down");
  strcpy(s[69]," l            : Locate Current Song");
  strcpy(s[70]," L            : Autolocate Current Song");
  strcpy(s[71]," p            : Playlist Options");
  strcpy(s[72]," p,n          : New Playlist");
  strcpy(s[73]," p,l          : Load Playlist");
  strcpy(s[74]," p,s          : Save Playlist");
  strcpy(s[75]," p,i          : Import Playlist");
  strcpy(s[76]," p,e          : Export Playlist");
  strcpy(s[77]," E            : Edit playlist file entry");
  strcpy(s[78]," n            : Refresh list");
  strcpy(s[79]," ;            : On/Off save playlist position on exit");
  strcpy(s[80],"");
  strcpy(s[81],"JUMP TO FILE");
  strcpy(s[82]," <ENTER>      : Play");
  strcpy(s[83]," <SPACE BAR>  : Set as next");
  strcpy(s[84]," <TAB>        : Add/Remove to/from filter");
  strcpy(s[85]," F            : Add/Remove all songs to filter");
  strcpy(s[86]," i            : ID3 TAG Edditor");
  strcpy(s[87]," ESC or q     : Close window");
  strcpy(s[88],"");
  strcpy(s[89],"EQUALIZER WINDOW");
  strcpy(s[90]," <PAGE UP>    : Up ALL");
  strcpy(s[91]," <PAGE DOWN>  : Down ALL");
  strcpy(s[92]," a/z          : Up/Down Band #1");
  strcpy(s[93]," s/x          : Up/Down Band #2");
  strcpy(s[94]," d/c          : Up/Down Band #3");
  strcpy(s[95]," f/v          : Up/Down Band #4");
  strcpy(s[96]," g/b          : Up/Down Band #5");
  strcpy(s[97]," h/n          : Up/Down Band #6");
  strcpy(s[98]," j/m          : Up/Down Band #7");
  strcpy(s[99]," k/,          : Up/Down Band #8");
  strcpy(s[100]," l/.          : Up/Down Band #9");
  strcpy(s[101]," ;//          : Up/Down Band #10");
  strcpy(s[102]," r            : Set all bands to 0 (reset equalizer)");
  strcpy(s[103]," L            : Load Preset");
  strcpy(s[104]," S            : Save Preset");
  strcpy(s[105]," I            : Import Preset(s)");
  strcpy(s[106]," D            : Delete Preset(s)");
  strcpy(s[107]," A            : On/Off Automatic Equalizer");
  strcpy(s[108],"");
  strcpy(s[109],"STATISTICS");
  strcpy(s[110]," R            : Reset current session statistics");
  strcpy(s[111],"");
  strcpy(s[112],"SPECIAL FUNCTIONS");
  strcpy(s[113]," P            : Save playlist for MP3 CD Player");
  strcpy(s[114],"                * Save your playlist (p,s). Make a");
  strcpy(s[115],"                  new playlist (p,n).Load Directory (D)");
  strcpy(s[116],"                  from the CD in your playlist.");
  strcpy(s[117],"                * Tested on JazzPIPER MCD650S");
  strcpy(s[118],"");
  strcpy(s[119],"PLAYER MODES");
  strcpy(s[120]," Normal       : Next song in playlist (don\'t shuffle)");
  strcpy(s[121]," Shuffle      : Random next song (shuffle)");
  strcpy(s[122]," Next Song    : Next song is already selected");
  strcpy(s[123]," Filter       : There are files in the filter");
  strcpy(s[124]," P-Filter     : The filter is persistent");
  strcpy(s[125]," Password     : Display is locked with password");
  strcpy(s[126]," Sleep        : Shut Down at a specific time");
  strcpy(s[127]," Shut Down    : Shut Down after current song");
  strcpy(s[128],"");
  strcpy(s[129],"STATUS BAR");
  strcpy(s[130]," Mode 1       : Displays mode, vol, pcm, bal & flags");
  strcpy(s[131]," Mode 2       : Displays next song's name");
  strcpy(s[132]," Mode 3       : Displays nr of files in filter");
  strcpy(s[133]," Mode 4       : Displays alram start & stop time");
  strcpy(s[134]," Mode 5       : Displays shut down time");
  strcpy(s[135]," Flags   S - save playlist on exit");
  strcpy(s[136],"         E - auto equalizer");
  strcpy(s[137],"         L - autolocate current song");
  strcpy(s[138],"         P - use persistent filter");
  strcpy(s[139],"         A - Alarm is set");
  const int help_lines=139;
